# Generated by Django 4.1.1 on 2022-12-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bountypost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunter',
            name='total_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
